module.exports = [
  {
    species: "Bengal Tiger",
    extinct: false,
    location: "India",
    lifeExpectancy: "10-15 years",
  },
  {
    species: "Dodo Bird",
    extinct: true,
    location: "Mauritius",
    lifeExpectancy: "Unknown",
  },
  {
    species: "Blue Whale",
    extinct: false,
    location: "Oceans worldwide",
    lifeExpectancy: "70-90 years",
  },
  {
    species: "Snow Leopard",
    extinct: false,
    location: "Central Asia",
    lifeExpectancy: "15-18 years",
  },
  {
    species: "Tasmanian Tiger",
    extinct: true,
    location: "Tasmania",
    lifeExpectancy: "5-7 years",
  },
  {
    species: "Komodo Dragon",
    extinct: false,
    location: "Indonesia",
    lifeExpectancy: "20-30 years",
  },
  {
    species: "African Elephant",
    extinct: false,
    location: "Africa",
    lifeExpectancy: "60-70 years",
  },
  {
    species: "Galápagos Tortoise",
    extinct: false,
    location: "Galápagos Islands",
    lifeExpectancy: "100-150 years",
  },
  {
    species: "Red Panda",
    extinct: false,
    location: "Himalayas and Southeast Asia",
    lifeExpectancy: "8-12 years",
  },
  {
    species: "Quagga",
    extinct: true,
    location: "South Africa",
    lifeExpectancy: "Unknown",
  },
  {
    species: "Giant Panda",
    extinct: false,
    location: "China",
    lifeExpectancy: "20 years",
  },
  {
    species: "Javan Rhino",
    extinct: false,
    location: "Java",
    lifeExpectancy: "30-45 years",
  },
  {
    species: "Arctic Fox",
    extinct: false,
    location: "Arctic regions",
    lifeExpectancy: "3-6 years",
  },
  {
    species: "Mountain Gorilla",
    extinct: false,
    location: "Central Africa",
    lifeExpectancy: "35-40 years",
  },
  {
    species: "Koala",
    extinct: false,
    location: "Australia",
    lifeExpectancy: "13-18 years",
  },
  {
    species: "Vaquita",
    extinct: false,
    location: "Gulf of California",
    lifeExpectancy: "Up to 21 years",
  },
  {
    species: "Pangolin",
    extinct: false,
    location: "Africa, Asia",
    lifeExpectancy: "Unknown",
  },
  {
    species: "Manatee",
    extinct: false,
    location: "North and Central America, Africa",
    lifeExpectancy: "40-60 years",
  },
  {
    species: "Fennec Fox",
    extinct: false,
    location: "Sahara Desert",
    lifeExpectancy: "Up to 14 years",
  },
  {
    species: "Giraffe",
    extinct: false,
    location: "Africa",
    lifeExpectancy: "20-25 years",
  },
  {
    species: "Cheetah",
    extinct: false,
    location: "Africa, Iran",
    lifeExpectancy: "10-12 years",
  },
  {
    species: "Golden Lion Tamarin",
    extinct: false,
    location: "Brazil",
    lifeExpectancy: "15 years",
  },
  {
    species: "Narwhal",
    extinct: false,
    location: "Arctic waters",
    lifeExpectancy: "50-60 years",
  },
  {
    species: "Ocelot",
    extinct: false,
    location: "South America, Central America, Mexico",
    lifeExpectancy: "10-13 years",
  },
  {
    species: "Quokka",
    extinct: false,
    location: "Australia",
    lifeExpectancy: "10 years",
  },
  {
    species: "Peregrine Falcon",
    extinct: false,
    location: "Worldwide",
    lifeExpectancy: "8-15 years",
  },
  {
    species: "Leatherback Sea Turtle",
    extinct: false,
    location: "Worldwide",
    lifeExpectancy: "Up to 100 years",
  },
  {
    species: "Hammerhead Shark",
    extinct: false,
    location: "Worldwide",
    lifeExpectancy: "20-30 years",
  },
  {
    species: "Kangaroo",
    extinct: false,
    location: "Australia",
    lifeExpectancy: "6-8 years",
  },
  {
    species: "Albatross",
    extinct: false,
    location: "Oceans worldwide",
    lifeExpectancy: "40-60 years",
  },
  {
    species: "Sloth",
    extinct: false,
    location: "Central and South America",
    lifeExpectancy: "20-30 years",
  },
  {
    species: "Polar Bear",
    extinct: false,
    location: "Arctic Circle",
    lifeExpectancy: "20-30 years",
  },
  {
    species: "Gorilla",
    extinct: false,
    location: "Central Africa",
    lifeExpectancy: "35-40 years",
  },
  {
    species: "Toucan",
    extinct: false,
    location: "Central and South America",
    lifeExpectancy: "20 years",
  },
  {
    species: "Black Rhino",
    extinct: false,
    location: "Africa",
    lifeExpectancy: "35-50 years",
  },
  {
    species: "Wolverine",
    extinct: false,
    location: "North America, Europe, Asia",
    lifeExpectancy: "Up to 13 years",
  },
  {
    species: "Ostrich",
    extinct: false,
    location: "Africa",
    lifeExpectancy: "40-45 years",
  },
  {
    species: "Axolotl",
    extinct: false,
    location: "Mexico",
    lifeExpectancy: "15 years",
  },
  {
    species: "Raccoon",
    extinct: false,
    location: "North America",
    lifeExpectancy: "2-3 years",
  },
];
